Repository AY2425S2-CS2113-W13-1/tp, pull requests merged in 2025-03, with the labels that each got.

#35 Add skeleton codes for Round class
  src/main/java/Javatro/Round.java
Labels: type.Task

#65 Fix HoldingHand Play() and Discard()
  src/main/java/Javatro/HoldingHand.java
  src/main/java/Javatro/Round.java
  src/test/java/Javatro/HoldingHandTest.java
Labels: type.Bug, severity.High

#75 Fix Exceeded Limit Text Occuring
  src/main/java/javatro_core/HoldingHand.java
  src/main/java/javatro_manager/HelpCommand.java
  src/main/java/javatro_manager/HelpHowToPlayCommand.java
  src/main/java/javatro_manager/HelpIntroCommand.java
  src/main/java/javatro_manager/HelpRulesCommand.java
  src/main/java/javatro_manager/HelpTipsCommand.java
  src/main/java/javatro_view/HelpScreen.java
  src/main/java/javatro_view/JavatroView.java
  src/main/java/javatro_view/StartScreen.java
  src/test/java/Javatro/HoldingHandTest.java
Labels: type.Bug

#78 Structure Enhancement II
  src/main/java/Javatro/Core/JavatroCore.java
  src/main/java/Javatro/Javatro.java
  src/main/java/Javatro/Manager/HelpCommand.java
  src/main/java/Javatro/Manager/HelpIntroCommand.java
  src/main/java/Javatro/Manager/JavatroManager.java
  src/main/java/Javatro/Manager/LoadOptionsScreenCommand.java
  src/main/java/Javatro/Manager/Options/DiscardCardsOption.java
  src/main/java/Javatro/Manager/Options/ExitGameOption.java
  src/main/java/Javatro/Manager/Options/HelpHowToPlayOption.java
  src/main/java/Javatro/Manager/Options/HelpIntroOption.java
  src/main/java/Javatro/Manager/Options/HelpOption.java
  src/main/java/Javatro/Manager/Options/HelpRulesOption.java
  src/main/java/Javatro/Manager/Options/HelpTipsOption.java
  src/main/java/Javatro/Manager/Options/LoadGameScreenOption.java
  src/main/java/Javatro/Manager/Options/LoadStartScreenOption.java
  src/main/java/Javatro/Manager/Options/MakeSelectionOption.java
  src/main/java/Javatro/Manager/Options/Option.java
  src/main/java/Javatro/Manager/Options/PlayCardsOption.java
  src/main/java/Javatro/Manager/Options/ResumeGameOption.java
  src/main/java/Javatro/Parser/Parser.java
  src/main/java/Javatro/UI/Screens/GameScreen.java
  src/main/java/Javatro/UI/Screens/HelpIntroScreen.java
  src/main/java/Javatro/UI/Screens/HelpScreen.java
  src/main/java/Javatro/UI/Screens/Screen.java
  src/main/java/Javatro/UI/Screens/SelectCardsToDiscardScreen.java
  src/main/java/Javatro/UI/Screens/SelectCardsToPlayScreen.java
  src/main/java/Javatro/UI/Screens/SelectionScreen.java
  src/main/java/Javatro/UI/Screens/StartScreen.java
  src/main/java/Javatro/UI/UI.java
  src/main/java/Javatro/UI/package-info.java
  src/main/java/Javatro/View/HelpScreen.java
  src/main/java/Javatro/View/OptionScreen.java
Labels: priority.High, severity.High

#84 Improve Test Coverage and Squash Bugs
  build.gradle
  src/main/java/javatro/core/HoldingHand.java
  src/main/java/javatro/manager/options/ExitGameOption.java
  src/test/java/javatro/core/RoundTest.java
  src/test/java/javatro/display/screens/ScreenTest.java
Labels: type.Enhancement

#88 Add Checkered Deck
  src/main/java/javatro/core/Deck.java
Labels: type.Enhancement

#100 UI Revamp 4
  src/main/java/javatro/core/HandResult.java
  src/main/java/javatro/core/PlanetCard.java
  src/main/java/javatro/core/PokerHand.java
  src/main/java/javatro/core/Round.java
  src/main/java/javatro/display/Parser.java
  src/main/java/javatro/display/UI.java
  src/main/java/javatro/display/screens/CardSelectScreen.java
  src/main/java/javatro/display/screens/DeckScreen.java
  src/main/java/javatro/display/screens/GameScreen.java
  src/main/java/javatro/display/screens/HelpScreen.java
  src/main/java/javatro/display/screens/PokerHandScreen.java
  src/main/java/javatro/manager/options/DeckOption.java
  src/main/java/javatro/manager/options/ExitGameOption.java
  src/main/java/javatro/manager/options/HelpHowOption.java
  src/main/java/javatro/manager/options/HelpIntroOption.java
  src/main/java/javatro/manager/options/HelpMenuOption.java
  src/main/java/javatro/manager/options/HelpRulesOption.java
  src/main/java/javatro/manager/options/HelpTipsOption.java
  src/main/java/javatro/manager/options/PokerHandOption.java
  src/main/java/javatro/manager/options/ReturnOption.java
  src/test/java/javatro/core/handResultTest.java
Labels: type.Enhancement, type.Task, priority.High

#95 Swetha-AnteandBlind
  build.gradle
  src/main/java/javatro/core/Ante.java
  src/main/java/javatro/core/JavatroCore.java
  src/main/java/javatro/core/JavatroException.java
  src/main/java/javatro/core/Round.java
  src/main/java/javatro/display/UI.java
  src/main/java/javatro/display/screens/BlindScreen.java
  src/main/java/javatro/display/screens/GameScreen.java
  src/main/java/javatro/manager/JavatroManager.java
  src/main/java/javatro/manager/options/AcceptBlindOption.java
  src/main/java/javatro/manager/options/DiscardCardOption.java
  src/main/java/javatro/manager/options/HelpHowOption.java
  src/main/java/javatro/manager/options/NextRoundOption.java
  src/main/java/javatro/manager/options/PlayCardOption.java
  src/main/java/javatro/manager/options/RejectBlindOption.java
  src/main/java/javatro/manager/options/ResumeGameOption.java
  src/main/java/javatro/manager/options/StartGameOption.java
  src/test/java/javatro/core/AnteTest.java
Labels: type.Task, priority.High

#99 Add Different Deck Types
  src/main/java/javatro/core/Ante.java
  src/main/java/javatro/core/Card.java
  src/main/java/javatro/core/Deck.java
  src/main/java/javatro/core/HoldingHand.java
  src/main/java/javatro/core/JavatroCore.java
  src/main/java/javatro/core/PlanetCard.java
  src/main/java/javatro/core/Round.java
  src/main/java/javatro/core/package-info.java
  src/main/java/javatro/display/UI.java
  src/main/java/javatro/display/screens/BlindScreen.java
  src/main/java/javatro/display/screens/CardSelectScreen.java
  src/main/java/javatro/display/screens/DeckScreen.java
  src/main/java/javatro/display/screens/GameScreen.java
  src/main/java/javatro/display/screens/HelpScreen.java
  src/main/java/javatro/display/screens/PokerHandScreen.java
  src/main/java/javatro/display/screens/SelectDeckScreen.java
  src/main/java/javatro/manager/JavatroManager.java
  src/main/java/javatro/manager/options/AbandonedDeckSelectOption.java
  src/main/java/javatro/manager/options/AcceptBlindOption.java
  src/main/java/javatro/manager/options/BlueDeckSelectOption.java
  src/main/java/javatro/manager/options/CheckeredDeckSelectOption.java
  src/main/java/javatro/manager/options/HelpHowOption.java
  src/main/java/javatro/manager/options/NextRoundOption.java
  src/main/java/javatro/manager/options/RedDeckSelectOption.java
  src/main/java/javatro/manager/options/RejectBlindOption.java
  src/main/java/javatro/manager/options/StartGameOption.java
  src/test/java/javatro/core/AnteTest.java
  src/test/java/javatro/core/DeckTest.java
  src/test/java/javatro/core/HoldingHandTest.java
  src/test/java/javatro/core/RoundTest.java
Labels: priority.Medium

#102 Add Jokers and Planet Cards
  src/main/java/javatro/core/Ante.java
  src/main/java/javatro/core/JavatroCore.java
  src/main/java/javatro/core/JavatroException.java
  src/main/java/javatro/core/Round.java
  src/main/java/javatro/core/Score.java
  src/main/java/javatro/core/jokers/HeldJokers.java
  src/main/java/javatro/core/jokers/Joker.java
  src/main/java/javatro/core/jokers/JokerFactory.java
  src/main/java/javatro/core/jokers/addchip/OddToddJoker.java
  src/main/java/javatro/core/jokers/addchip/ScaryFaceJoker.java
  src/main/java/javatro/core/jokers/addmult/CounterJoker.java
  src/main/java/javatro/core/jokers/addmult/GluttonousJoker.java
  src/main/java/javatro/core/jokers/addmult/GreedyJoker.java
  src/main/java/javatro/core/jokers/addmult/HalfJoker.java
  src/main/java/javatro/core/jokers/addmult/LustyJoker.java
  src/main/java/javatro/core/jokers/addmult/WrathfulJoker.java
  src/main/java/javatro/display/UI.java
  src/main/java/javatro/display/screens/BlindScreen.java
  src/main/java/javatro/display/screens/GameScreen.java
  src/main/java/javatro/manager/JavatroManager.java
  src/main/java/javatro/manager/options/AbandonedDeckSelectOption.java
  src/main/java/javatro/manager/options/AcceptBlindOption.java
  src/main/java/javatro/manager/options/BlueDeckSelectOption.java
  src/main/java/javatro/manager/options/CheckeredDeckSelectOption.java
  src/main/java/javatro/manager/options/NextRoundOption.java
  src/main/java/javatro/manager/options/RedDeckSelectOption.java
  src/main/java/javatro/manager/options/RejectBlindOption.java
  src/test/java/javatro/core/AnteTest.java
  src/test/java/javatro/core/RoundTest.java
  src/test/java/javatro/core/ScoreTest.java
  src/test/java/javatro/core/jokers/HeldJokersTest.java
  src/test/java/javatro/core/jokers/addchip/OddToddJokerTest.java
  src/test/java/javatro/core/jokers/addchip/ScaryFaceJokerTest.java
  src/test/java/javatro/core/jokers/addmult/HalfJokerTest.java
Labels: type.Task

#118 Fix Discards for HoldingHand
  src/main/java/javatro/core/Round.java
  src/main/java/javatro/core/RoundActions.java
  src/main/java/javatro/display/screens/GameScreen.java
Labels: type.Bug

#127 Fix "The Window" description being wrong
  src/main/java/javatro/core/Round.java
Labels: type.Bug

#130 Fix Empty Deck Exception not Handled
  src/main/java/javatro/core/Deck.java
  src/main/java/javatro/core/JavatroException.java
  src/main/java/javatro/core/Round.java
  src/test/java/javatro/core/RoundTest.java
Labels: type.Bug
