Repository AY2425S2-CS2113-W13-1/tp, pull requests merged in 2025-04, with the labels that each got.

#142 User Guide Base
  .gitignore
  Gemfile
  _config.yml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/blind_screen.png
  docs/boss_blind.png
  docs/deck_selection.png
  docs/deck_view.png
  docs/dg_images/ante_2.png
  docs/dg_images/ante_class_diagram.png
  docs/dg_images/application_init.png
  docs/dg_images/architecture.png
  docs/dg_images/cardrenderer_class.png
  docs/dg_images/cardrenderer_sequence_diagram.png
  docs/dg_images/gameplay_enhance_diagram.png
  docs/dg_images/gameplay_interaction_sequence_diagram.png
  docs/dg_images/gameplay_sequence.png
  docs/dg_images/logic_sequence.png
  docs/dg_images/option_sequence.png
  docs/dg_images/option_sequence_2.png
  docs/dg_images/overall_scoring.png
  docs/dg_images/round_1.png
  docs/dg_images/round_2.png
  docs/dg_images/score_1.png
  docs/dg_images/score_2.png
  docs/dg_images/score_3.png
  docs/dg_images/score_4.png
  docs/dg_images/score_5.png
  docs/dg_images/ui_screens_diagram.png
  docs/discard_card.png
  docs/game_screen.png
  docs/play_card.png
  docs/poker_hand_screen.png
  docs/start_screen.png
  docs/win_joker.png
  docs/win_planet_card.png
Labels: type.Story, priority.High

#207 Tests and Bug fixes
  src/main/java/javatro/core/Card.java
  src/main/java/javatro/core/HandResult.java
  src/main/java/javatro/core/PlanetCard.java
  src/main/java/javatro/core/PokerHand.java
  src/main/java/javatro/display/Parser.java
  src/main/java/javatro/display/ansi/planet_earth.txt
  src/main/java/javatro/display/ansi/planet_planet_x.txt
  src/main/java/javatro/display/package-info.java
  src/main/java/javatro/manager/JavatroManager.java
  src/main/java/javatro/manager/options/CardSelectOption.java
  src/main/java/javatro/manager/options/DeckSelectOption.java
  src/main/java/javatro/manager/options/DeckViewOption.java
  src/main/java/javatro/manager/options/DiscardCardOption.java
  src/main/java/javatro/manager/options/ExitGameOption.java
  src/main/java/javatro/manager/options/MainMenuOption.java
  src/main/java/javatro/manager/options/Option.java
  src/main/java/javatro/manager/options/PlayCardOption.java
  src/main/java/javatro/manager/options/PokerHandOption.java
  src/main/java/javatro/manager/options/ResumeGameOption.java
  src/main/java/javatro/manager/options/ReturnOption.java
  src/main/java/javatro/manager/options/SortByRankOption.java
  src/main/java/javatro/manager/options/SortBySuitOption.java
  src/main/java/javatro/manager/options/StartGameOption.java
  src/test/java/javatro/core/CardTest.java
  src/test/java/javatro/core/PlanetCardTest.java
  src/test/java/javatro/core/PokerHandTest.java
  src/test/java/javatro/core/handResultTest.java
  src/test/java/javatro/display/screens/ScreenTest.java
Labels: type.Enhancement, type.Task, priority.High

#211 Revamped UG
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/blind_screen.png
  docs/boss_blind.png
  docs/deck_selection.png
  docs/deck_view.png
  docs/dg_diagrams/Round CD.md
  docs/dg_diagrams/Round SD.md
  docs/dg_diagrams/RoundActions SD.md
  docs/discard_card.png
  docs/game_screen.png
  docs/img.png
  docs/img_1.png
  docs/img_2.png
  docs/img_3.png
  docs/javatro_logo.png
  docs/play_card.png
  docs/poker_hand_screen.png
  docs/start_screen.png
  docs/team/johndoe.md
  docs/ug_images/blind_menu.png
  docs/ug_images/boss_blind.png
  docs/ug_images/deck_select.png
  docs/ug_images/deck_view.png
  docs/ug_images/discard_card_rank.png
  docs/ug_images/discarded_card.png
  docs/ug_images/main_menu.png
  docs/ug_images/play_card_suit.png
  docs/ug_images/played_card.png
  docs/ug_images/poker_hand.png
  docs/ug_images/small_blind.png
  docs/ug_images/win_joker.png
  docs/ug_images/win_planet_card.png
  docs/win_joker.png
  docs/win_planet_card.png
  src/main/java/javatro/display/UI.java
Labels: type.Enhancement, type.Task, priority.High

#208 Javatro Storage
  .gitignore
  src/main/java/javatro/Javatro.java
  src/main/java/javatro/core/Ante.java
  src/main/java/javatro/core/Deck.java
  src/main/java/javatro/core/JavatroCore.java
  src/main/java/javatro/core/PlanetCard.java
  src/main/java/javatro/core/jokers/HeldJokers.java
  src/main/java/javatro/core/jokers/Joker.java
  src/main/java/javatro/core/jokers/addchip/OddToddJoker.java
  src/main/java/javatro/core/jokers/addchip/ScaryFaceJoker.java
  src/main/java/javatro/core/jokers/addmult/AbstractJoker.java
  src/main/java/javatro/core/jokers/addmult/GluttonousJoker.java
  src/main/java/javatro/core/jokers/addmult/GreedyJoker.java
  src/main/java/javatro/core/jokers/addmult/HalfJoker.java
  src/main/java/javatro/core/jokers/addmult/LustyJoker.java
  src/main/java/javatro/core/jokers/addmult/WrathfulJoker.java
  src/main/java/javatro/core/round/Round.java
  src/main/java/javatro/core/round/RoundObservable.java
  src/main/java/javatro/display/UI.java
  src/main/java/javatro/display/ansi/DeckArt.java
  src/main/java/javatro/display/screens/BlindSelectScreen.java
  src/main/java/javatro/display/screens/JumpToRunScreen.java
  src/main/java/javatro/display/screens/RunSelectScreen.java
  src/main/java/javatro/display/screens/StartScreen.java
  src/main/java/javatro/manager/options/AcceptBlindOption.java
  src/main/java/javatro/manager/options/DeckSelectOption.java
  src/main/java/javatro/manager/options/LoadJumpToRunScreenOption.java
  src/main/java/javatro/manager/options/LoadRunSelectOption.java
  src/main/java/javatro/manager/options/Option.java
  src/main/java/javatro/manager/options/SeeNextRunOption.java
  src/main/java/javatro/manager/options/SeePreviousRun.java
  src/main/java/javatro/manager/options/SelectRunNumberOption.java
  src/main/java/javatro/manager/options/StartGameOption.java
  src/main/java/javatro/manager/options/StartRunNumberOption.java
  src/main/java/javatro/storage/HashUtil.java
  src/main/java/javatro/storage/Storage.java
Labels: type.Story, priority.High

#216 Screen Tests
  src/main/java/javatro/audioplayer/AudioPlayer.java
  src/main/java/javatro/core/PlanetCard.java
  src/main/java/javatro/core/jokers/HeldJokers.java
  src/main/java/javatro/core/round/RoundObservable.java
  src/main/java/javatro/display/Parser.java
  src/main/java/javatro/display/screens/DeckViewScreen.java
  src/main/java/javatro/display/screens/GameScreen.java
  src/main/java/javatro/display/screens/Screen.java
  src/main/java/javatro/display/screens/WinGameScreen.java
  src/main/java/javatro/manager/JavatroManager.java
  src/main/java/javatro/manager/options/DeckSelectOption.java
  src/main/java/javatro/manager/options/StartRunOption.java
  src/main/java/javatro/manager/options/ViewRunOption.java
  src/main/java/javatro/storage/Storage.java
  src/main/java/javatro/utilities/csvutils/CSVUtils.java
  src/main/java/javatro/utilities/outpututils/OutputUtils.java
  src/test/java/javatro/audioplayer/AudioPlayerTest.java
  src/test/java/javatro/core/PlanetCardTest.java
  src/test/java/javatro/core/jokers/HeldJokersTest.java
  src/test/java/javatro/core/round/RoundTest.java
  src/test/java/javatro/display/CardRendererTest.java
  src/test/java/javatro/display/ParserTest.java
  src/test/java/javatro/display/UIPrintANSITest.java
  src/test/java/javatro/display/screens/CardSelectScreenTest.java
  src/test/java/javatro/display/screens/DeckViewScreenTest.java
  src/test/java/javatro/display/screens/GameScreenTest.java
  src/test/java/javatro/display/screens/LoseScreenTest.java
  src/test/java/javatro/display/screens/PlayCardScreenTest.java
  src/test/java/javatro/display/screens/RunListScreenTest.java
  src/test/java/javatro/display/screens/RunSelectScreenTest.java
  src/test/java/javatro/display/screens/ScreenTest.java
  src/test/java/javatro/display/screens/StartScreenTest.java
  src/test/java/javatro/display/screens/WinGameScreenTest.java
  src/test/java/javatro/display/screens/WinRoundScreenTest.java
Labels: type.Enhancement, priority.High
